name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: false
        msystem: MINGW64 
        install: >-
          curl
          git            
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-flac
          mingw-w64-x86_64-freetype
          mingw-w64-x86_64-glib2
          mingw-w64-x86_64-graphite2
          mingw-w64-x86_64-harfbuzz
          mingw-w64-x86_64-libjpeg-turbo
          mingw-w64-x86_64-libmysofa
          mingw-w64-x86_64-libogg
          mingw-w64-x86_64-libpng
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-mpdecimal
          mingw-w64-x86_64-ncurses
          mingw-w64-x86_64-openal
          mingw-w64-x86_64-pcre2
          mingw-w64-x86_64-python
          mingw-w64-x86_64-readline
          mingw-w64-x86_64-sqlite3
          mingw-w64-x86_64-tcl
          mingw-w64-x86_64-termcap  
          mingw-w64-x86_64-tk
          mingw-w64-x86_64-tzdata
          mingw-w64-x86_64-wineditline
    - shell: msys2 {0}
      run: |
        pacman  -S mingw-w64-x86_64-sfml
#       makepkg-mingw -sCLfc --noconfirm --noprogressbar
    - uses: actions/checkout@v3
#     - name: install sfml
#       run: |
#         gcc --version
#         pacman -S mingw-w64-x86_64-sfml
    - name: make
      run: make -f Makefile.windows
    - name: make test
      run: make -f Makefile.windows test
#    - name: make check
#      run: make  -f Makefile.windows check
#    - name: make distcheck
#      run: make  -f Makefile.windows  distcheck
