name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: false
        msystem: UCRT64
        install: >-
          curl
          git
    - shell: msys2 {0}
      run: |
        makepkg-mingw -sCLfc --noconfirm --noprogressbar
        pacman  -S mingw-w64-x86_64-sfml
    - uses: actions/checkout@v3
#     - name: install sfml
#       run: |
#         gcc --version
#         pacman -S mingw-w64-x86_64-sfml
    - name: make
      run: make -f Makefile.windows
    - name: make test
      run: make -f Makefile.windows test
#    - name: make check
#      run: make  -f Makefile.windows check
#    - name: make distcheck
#      run: make  -f Makefile.windows  distcheck
