name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
#    - name: configure
#      run: ./configure
#    - name: install sfml
#      run: pacman -S mingw-w64-x86_64-sfml
    - name: make
      run: make -f Makefile.windows
    - name: make test
      run: make -f Makefile.windows test
#    - name: make check
#      run: make  -f Makefile.windows check
#    - name: make distcheck
#      run: make  -f Makefile.windows  distcheck
