name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: false
        msystem: MINGW64 
        install: >-
          curl
          git            
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-flac-1.4.2-1  mingw-w64-x86_64-freetype-2.13.0-1  mingw-w64-x86_64-glib2-2.76.3-1  mingw-w64-x86_64-graphite2-1.3.14-2  mingw-w64-x86_64-harfbuzz-7.3.0-1  mingw-w64-x86_64-libjpeg-turbo-2.1.5.1-1  mingw-w64-x86_64-libmysofa-1.3.1-1  mingw-w64-x86_64-libogg-1.3.5-1  mingw-w64-x86_64-libpng-1.6.39-1  mingw-w64-x86_64-libvorbis-1.3.7-1  mingw-w64-x86_64-mpdecimal-2.5.1-1  mingw-w64-x86_64-ncurses-6.4.20230211-1  mingw-w64-x86_64-openal-1.23.1-1  mingw-w64-x86_64-pcre2-10.42-1  mingw-w64-x86_64-python-3.10.11-1  mingw-w64-x86_64-readline-8.2.001-6  mingw-w64-x86_64-sqlite3-3.42.0-1  mingw-w64-x86_64-tcl-8.6.12-2  mingw-w64-x86_64-termcap-1.3.1-6  mingw-w64-x86_64-tk-8.6.12-1  mingw-w64-x86_64-tzdata-2023c-1  mingw-w64-x86_64-wineditline-2.206-1  mingw-w64-x86_64-sfml-2.5.1-4
    - shell: msys2 {0}
      run: |
        pacman  -S mingw-w64-x86_64-sfml
#       makepkg-mingw -sCLfc --noconfirm --noprogressbar
    - uses: actions/checkout@v3
#     - name: install sfml
#       run: |
#         gcc --version
#         pacman -S mingw-w64-x86_64-sfml
    - name: make
      run: make -f Makefile.windows
    - name: make test
      run: make -f Makefile.windows test
#    - name: make check
#      run: make  -f Makefile.windows check
#    - name: make distcheck
#      run: make  -f Makefile.windows  distcheck
